services:
 identitydb:
    container_name: identitydb
    environment:
      SA_PASSWORD: "Dibakor46@"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - identitydb-data:/var/opt/mssql  

 identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ConnectionStrings__DefaultConnection=Server=identitydb;Database=identitydb;User Id=sa;Password=Dibakor46@;TrustServerCertificate=True;"
      - "Jwt__Key=super_secure_secret_key_1234567890!@#"
      - "Jwt__Issuer=ecommerce.identity"
      - "Jwt__Audience=ecommerce.clients"
    depends_on:
      - identitydb          
    ports: 
      - "8005:8080"

 ocelot.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "Jwt__Key=super_secure_secret_key_1234567890!@#"
      - "Jwt__Issuer=ecommerce.identity"
      - "Jwt__Audience=ecommerce.clients"
    depends_on:
      - identity
    ports:
      - "8010:8080"                 
