services:
 identitydb:
    image: mcr.microsoft.com/mssql/server:2022-latest

 identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
 
 ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
volumes:
 identitydb-data:
 